esl/amoc

ansible/group_vars/all
ansible/roles/amoc/templates/app.config.j2
rebar.config
relx.config
src/amoc.app.src
src/amoc_annotations.erl
src/amoc_app.erl
src/amoc_dist.erl
src/amoc_event.erl
src/amoc_sup.erl

This small extension introduces Graphite annotations for actions taken on distributed tests (scenario start, addition and removal of users).

Graphite annotations

---

README.md
ansible.cfg
ansible/amoc-master.yml
ansible/amoc-prepare.yml
ansible/amoc-slaves.yml
ansible/group_vars/all
ansible/group_vars/amoc-master
ansible/group_vars/amoc-slave
ansible/roles/amoc/tasks/main.yml
ansible/roles/amoc/templates/app.config.j2
ansible/roles/amoc/templates/vm.args.j2
ansible/roles/prepare/tasks/main.yml
hosts
makefile
relx.config
src/amoc_annotations.erl
src/amoc_controller.erl
src/amoc_dist.erl
src/amoc_metrics.erl

Sorry for putting everything in one PR :( - these are changes made for the euc tutorial.

Simplify configuration

---

rebar.config
relx.config
src/amoc_sup.erl
src/amoc_user.erl
src/amoc_users_sup.erl

Additional fixes:
- fix deps to work with R18 and accept later versions of escalus
- clean relx setup

Make number of repetitions configurable

---

src/amoc_api.erl
src/amoc_api_scenario_handler.erl
test/amoc_api_scenario_handler_SUITE.erl
test/amoc_api_scenario_handler_SUITE_data/sample_test.erl

Add REST API scenarios handler

Simple api2 scenario handler

---

src/amoc_api_scenarios_handler.erl
test/amoc_api_scenarios_handler_SUITE.erl
test/amoc_api_scenarios_handler_SUITE_data/sample_test.erl

add HTTP API scenarios handler - modified module is responsible for listing available scenarios for amoc and uploading scenarios

Simple api2 scenarios handler

---

src/amoc_api_scenario_handler.erl
src/amoc_api_status_handler.erl
src/amoc_controller.erl
src/amoc_dist.erl
test/amoc_api_scenario_handler_SUITE.erl

Now if you want to get scenario status, yo will get status running on the whole
cluster, previously you get information from node.

Change way of getting scenario status

---

scenarios/mongoose_pubsub_docker.erl

There was a dialyzer error about unused functions in `start/1` because of infinite execution of one line. Now dialyzer doesn't report error.
Attention: please merge it after #38 !

Mongoose pubsub docker dialyzer fix

---

makefile
src/amoc_api_scenarios_handler.erl

During REST API development I forgot to call `code:purge/1` before loading new scenario.
Also I add new makefile target for console.

Add code:purge to scenarios API handler and make console target

---

src/amoc_networking.erl

This module adds initially function for getting available
ip addresses from host, that are in specified subnet.
It is used for retrieved useful information for scenario
modules.

Add new module with network helper functions

---

scenarios/mongoose_mam_read_and_send_msgs_with_metrics.erl
scenarios/mongoose_pubsub_docker.erl
scenarios/mongoose_simple_docker.erl
scenarios/mongoose_simple_reconnect.erl
scenarios/mongoose_simple_with_metrics.erl
src/amoc_metrics.erl
src/amoc_xmpp.erl
src/amoc_xmpp_handlers.erl

* improved `amoc_metrics` API
* new `amoc_xmpp` module with helper function
* new `amoc_xmpp_handlers` module with common handlers

Extract common parts to helper modules

---

scenarios/helpers/coordinator.erl
scenarios/mongoose_gdpr_remove.erl

More or less finished the scenario. It should be updated to run on clt-swarm, and also to use some new version of coordinator in the future.

Added GDPR remove scenario

---

rebar.config
rebar.lock
scenarios/mongoose_docker_one_to_one.erl
scenarios/mongoose_mam_read_and_send_msgs_with_metrics.erl
scenarios/mongoose_muc.erl
scenarios/mongoose_muc_light.erl
scenarios/mongoose_simple_reconnect.erl
scenarios/mongoose_simple_with_metrics.erl
src/amoc_xmpp.erl
src/amoc_xmpp_handlers.erl
src/amoc_xmpp_muc.erl

Add scenarios that can be used for testing MUC and MUC Light.
Also: rewrite stanza handlers for better reusability.

Add scenarios for groupchat

---

src/amoc_config.erl
src/amoc_config_validation.erl
src/amoc_coordinator.erl
src/amoc_coordinator_worker.erl
test/amoc_coordinator_SUITE.erl
test/config_SUITE.erl

amoc_coordinator allows to group users in a simple manner

Amoc coordinator

---

docker/amoc.sh
docker/run.sh
src/amoc_api_scenario_handler.erl
src/amoc_config.erl

This PR is a preparation for splitting amoc into pure amoc and repository with scenarios.

Amoc arsenal xmpp - part 1

---

scenarios/pubsub_pep.erl
scenarios/pubsub_simple.erl

Change in pubsub_simple and pubsub_pep to use new coordniator module.

Use amoc coordinator

---

scenarios/helpers/iq_metrics.erl
scenarios/pubsub_pep.erl
src/amoc.app.src

Had to change helper to gen_server because amoc doesn't have mnesia. I don't know if it makes any sense.

IQ metrics helper

---

scenarios/pubsub_pep.erl
scenarios/pubsub_simple.erl
src/amoc_coordinator.erl
src/amoc_coordinator_worker.erl
test/amoc_coordinator_SUITE.erl

minor changes to amoc_coordinator

adding N of coordinate items as part of coordination event

---

README.md
doc/amoc_coordinator.md

This PR attempts to document `amoc_coordinator` module.

Document amoc coordinator

---

priv/app.config
src/amoc_api_scenario_handler.erl
src/amoc_config.erl
src/amoc_controller.erl
src/amoc_metrics.erl
src/amoc_slave.erl
src/amoc_throttle_process.erl

In this PR logger is used for logging from Amoc while dependencies still use lager.

Use logger for logging from amoc

---

Makefile
doc/amoc_coordinator.md
doc/distributed-run.md
doc/local-run.md
integration_test/cleanup_containers.sh
integration_test/dummy_scenario.erl
integration_test/test_add_new_node.sh
integration_test/test_distribute_scenario.sh
integration_test/test_docker_image.sh
integration_test/test_run_scenario.sh
scenarios/throttle_test.erl
src/amoc.erl
src/amoc_controller.erl
src/amoc_distribution/amoc_cluster.erl
src/amoc_distribution/amoc_dist.erl
src/amoc_scenario.erl
src/amoc_sup.erl
src/amoc_throttle/amoc_throttle_controller.erl
src/amoc_user.erl
src/amoc_users_sup.erl
src/rest_api/amoc_api_scenario_handler.erl
src/rest_api/amoc_api_scenarios_handler.erl
test/amoc_api_scenario_handler_SUITE.erl
test/amoc_config_scenario_SUITE.erl

Amoc controller rework, all the REST APIs remained unchanged. however we should consider rework of the REST interfaces as they doesn't map well to the current codebase.

amoc_controller rework

---

Makefile

Updated `rebar3` to `./rebar3` for console command

Update console command

---

.travis.yml
Makefile
elvis.config
rebar.config
scenarios/throttle_test.erl
src/amoc_coordinator/amoc_coordinator.erl
src/amoc_coordinator/amoc_coordinator_worker.erl
src/amoc_distribution/amoc_cluster.erl
src/amoc_throttle/amoc_throttle.erl
src/amoc_throttle/amoc_throttle_controller.erl
src/amoc_throttle/amoc_throttle_process.erl
src/rest_api/amoc_api_logic_handler.erl
test/amoc_coordinator_SUITE.erl

integration of CI elvis verification.
no functional changes, mostly whitespaces.

Elvis integration

---

README.md
doc/configuration.md
doc/scenario.md

documentation update

---

src/amoc_scenario.erl

Use a proper ETS lookup instead of ranging over all the table entries.

amoc_scenarios ets table improvement

---

src/amoc.erl
src/amoc_app.erl
src/amoc_config/amoc_config.erl
src/amoc_config/amoc_config_env.erl
src/amoc_config/amoc_config_parser.erl
src/amoc_config/amoc_config_utils.erl
src/amoc_config/amoc_config_verification.erl
src/amoc_controller.erl
src/amoc_distribution/amoc_cluster.erl
src/amoc_distribution/amoc_dist.erl
src/amoc_scenario.erl
src/amoc_sup.erl
src/amoc_throttle/amoc_throttle.erl
src/amoc_throttle/amoc_throttle_controller.erl
src/amoc_throttle/amoc_throttle_process.erl
src/amoc_user.erl
src/amoc_users_sup.erl

These are all changes specially to make hexdocs (and everything else that uses hexdocs for that matter!) prettier. And also to make code more understandable in general.
Note btw that the license doesn't need to go onto every single file for Apache, see:
https://www.apache.org/legal/apply-license.html#copy-per-file

Docs improvements
