esl/amoc

ansible/roles/amoc/templates/app.config.j2
Including hostnames of all the slave nodes in the slaves' app.config file breaks detection of the master going down.
=> Don't include hosts list in slave's app.config

ansible/roles/amoc/templates/vm.args.j2, priv/vm.args
My recent tests shows that:
* with kernel polling we don't consume big amount of `system time`, without kernel polling it was up to 50% system time ... 
* latency decreased, test that measures time to deliver is significantly lower(up to 10x). I was load testing the mongoose_simple_with_metrics scenario, so look there for the time to deliver metric details.
=> enable kernel polling

makefile, src/amoc_dist.erl
Probably the eunit tests are not handled perfectly.
=> Ignore remote shell nodes during distributed actions

src/amoc_api_status_handler.erl, test/amoc_api_status_handler_SUITE.erl
When we do `GET /status` on response we have `{ node_status: up | down }` instead of `{ status: true | false }`.
=> Better REST API status description

src/amoc_api_node_handler.erl, src/amoc_dist.erl, test/amoc_api_node_handler_SUITE.erl
Now when we do `GET /nodes` we invoke function `amoc_dist:ping_nodes()`, and on response we get:
`
{
"nodes":
{
nodeName1: "up" | "down",
nodeName2:  "up" | "down"
...
}
`
=> Add node listing on GET /nodes

relx.config, run.sh, src/amoc_api_scenarios_handler.erl, test/amoc_api_scenarios_handler_SUITE.erl
To be able to show users source of scenario, we should include them in release. Directory "scenarios" is also used for storage scenarios uploaded by user.
=> Include scenario sources in release

src/amoc.app.src, src/amoc_api_scenario_handler.erl, src/amoc_api_scenarios_handler.erl, test/amoc_api_scenario_handler_SUITE.erl, test/amoc_api_scenarios_handler_SUITE.erl
Previously we have some bugs and problems with running uploaded scenario:
* there was no information that scenario is not started
* scenario crashes if it uses lager which need special compile flag during compilation
* if we compiled scenario then we couldn't load it because in one line we provide directory name as atom, not a string and we couldn't use scenario later.
=> Simple api2 run scenario fix

rebar.config, src/amoc.app.src, src/amoc_api_node_handler.erl, src/amoc_api_scenario_handler.erl, src/amoc_api_scenarios_handler.erl, src/amoc_api_status_handler.erl, test/amoc_api_node_handler_SUITE.erl, test/amoc_api_scenario_handler_SUITE.erl, test/amoc_api_scenarios_handler_SUITE.erl, test/amoc_api_status_handler_SUITE.erl
Previously we had jiffy and jsx. We don't need two JSON parsers, and we need to have jiffy, so now we use only jiffy in code.
=> Replace jsx with jiffy in amoc

rebar.config, scenarios/mongoose_pubsub_docker.erl, src/amoc.app.src, test/amoc_api_helper.erl, test/amoc_api_node_handler_SUITE.erl, test/amoc_api_scenario_handler_SUITE.erl, test/amoc_api_scenarios_handler_SUITE.erl, test/amoc_api_status_handler_SUITE.erl
Instead `httpc` we want to use `fusco` only for testing purpose.
We need it also because on Travis CI we have OTP 17.5 where `httpc` do not support `PATCH` requests.
=> Replace httpc with fusco

docker/Dockerfile
Before finilizing image creation we should remove building
dependencies such as clang, gcc or esl-erlang, as they are
not required for running Amoc. This makes image lighter
by around 0.5GB.
Also expose HTTP API port.
Also build image from master branch.
=> Remove Amoc building deps after creating release and expose port

relx.config
It solves probably #45 . Earlier we have that line in `relx.config` because we need to include `scenarios` dir when making a release, however this attempt also works.
=> Fix multiple scenarios dir generation on making release:

docker/config/sys.config.template, docker/run.sh
It would be nice to be able to set reporting endpoint's port by just passing env var into container.
=> Allow to set graphite endpoint's port for exometer in docker container

docker/Dockerfile, docker/run.sh
After switch to rebar3, default vm.args file was pulled from `priv/vm.args`. These vm.args contain `-name amoc` argument, so Erlang VM wanted to start with fully qualified domain name. However, in some environments, Docker containers don't know their own domain which prevented the BEAM from starting.
Docker image should have used the vm.args from `docker/config/vm.args`, but switch to rebar3 and invalid `ADD` directive prevented that file from being picked up by the release handler during startup.
This PR fixes the Dockerfile so that the correct vm.args is copied to container and used later by the release handler.
=> Fix Docker image startup

scenarios/mongoose_pubsub_docker.erl, scenarios/pubsub_simple.erl
This PR introduces the following changes:
- Fix bug (`escalus_connection:start` was expected a tuple with 4 fields instead of 3)
- Simple scenario for `pubsub`
=> Add pubsub simple scenario

src/amoc_controller.erl, src/amoc_dist.erl, src/amoc_scenario.erl, test/amoc_controller_SUITE.erl, test/amoc_controller_SUITE_data/test_scenario.erl
It's now possible to terminate a scenario at any moment via two
new scenario callbacks `valid/0` and `terminate/1`. The former
checks if the current scenario is still valid e.g. some metrics are
below a certain treshold and must return `continue` or `{stop, Reason}`.
The latter one implements the actual termination. It's called only
if `valid/0` returned `{stop, Reason}`. The reason is passed to
the terminate callback. When `continue` is returned nothing happens.
The both callbacks are optional. Validation is scheduled only if
both of them are implemented. By default, validation interval
equals 60s. It can be changed by setting `scenario_validation_interval`
application environment.
Validation logic happens in `amoc_controller` process only on a
"master" Amoc node and only in "distributed …
=> Allow to terminate a scenario when invalid

src/amoc_api_scenario_handler.erl, src/amoc_controller.erl, src/amoc_scenario.erl, test/amoc_api_scenario_handler_SUITE.erl, test/amoc_controller_SUITE.erl, test/amoc_controller_SUITE_data/test_scenario.erl
There is new `amoc_controller:add_batches/2` function that allows to add
users in batches according to some strategy. The function takes the
scenario module and the number of batches as parameters.
The strategy of adding users should be returned by `next_user_batch/2`
callback implemented in the scenario module. The callback is optional.
The batch index and the number of users added in the previous batch are
parmeters that are passed to the callback function.  The strategy is a
list of `{Node, NumOfUsers, Interarrival}`.
Batches are added every batch interval specified by `add_batch_interval`
application environment variable, which is 5 minutes by default.
Adding batches can be sheduled via HTTP API by specifying `batches` key
in a body request to `scenarios/$SCENARIO` endpoint.
Closes …
=> Make it possible to add users in batches

README.md, docker/config/vm.args, docker/run.sh
The paths with extra code can be passed via `AMOC_EXTRA_CODE_PATHS` env variable.
=> Allow to pass extra code paths to the container

README.md, REST_API_DOCS.md, src/amoc.app.src, src/amoc_api_scenario_handler.erl, src/amoc_controller.erl, src/amoc_dist.erl, src/amoc_scenario.erl, test/amoc_api_scenario_handler_SUITE.erl, test/amoc_controller_SUITE.erl, test/amoc_controller_SUITE_data/test_scenario.erl
This branch was originally created for storing helpers that are considered relevant for load testing MongooseIM on AWS, however, @michalwski has suggested someone else might find these helpful as well hence the PR.
Main enhancements:
1.  **Allow to terminate a scenario at any time**
It's now possible to terminate a scenario at any moment via two
new scenario callbacks `continue/0` and `terminate/1`. The former
checks if the current scenario is still valid e.g. some metrics are
below a certain treshold and must return `continue` or `{stop, Reason}`.
The latter one implements the actual termination. It's called only
if `continue/0` returned `{stop, Reason}`. The reason is passed to
the terminate callback. When `continue` is returned nothing happens.
The both callbacks are optional. Checking …
=> AWS load tests inspired improvements

rebar.config, scenarios/throttle_test.erl, src/amoc_dist.erl, src/amoc_metrics.erl, src/amoc_slave.erl, src/amoc_sup.erl, src/amoc_throttle.erl, src/amoc_throttle_controller.erl, src/amoc_throttle_process.erl
ensuring that amoc throttle works correctly in distributed environment.
tested manually using `throttle_test` scenario, works correctly for both `amoc_local:do/3` and `amoc_dist:do/4`.
=> Amoc throttle rework

.travis.yml, rebar.config, src/amoc_annotations.erl
This PR adds xref check to CI and fixes a call to undefined function from `amoc_annotations`.
=> Run xref on CI

doc/local-run.md
As the Makefile shows `make rel` resulting in a call to `rebar as prod tar`, the path of the resulting binary would be nested under the `prod` directory for the release.
=> Update path to binary in local-run documentation

Dockerfile, doc/http-api.md, rebar.config, rebar.lock, src/amoc_config/amoc_config.hrl, src/amoc_config/amoc_config_attributes.erl, src/amoc_config/amoc_config_scenario.erl, src/rest_api/amoc_api_logic_handler.erl, src/rest_api/amoc_api_scenario_status.erl, test/amoc_api_scenario_handler_SUITE.erl, test/amoc_api_scenarios_handler_SUITE.erl, test/scenario_template.hrl
Implementation of `/scenarios/{id}/info` and update of  `/scenarios/{id}` GET methods.
`/scenarios/{id}` is tested manually. I haven't extended tests for it since we are going to rework it in the next iteration.
=> Scenario descr rest api

doc/http-api.md, integration_test/test_run_scenario.sh, rebar.config, rebar.lock, src/amoc_distribution/amoc_dist.erl, src/rest_api/amoc_api_logic_handler.erl, src/rest_api/amoc_api_scenario_status.erl, test/amoc_api_execution_handler_SUITE.erl, test/amoc_api_scenario_handler_SUITE.erl
Follows the API definition: https://github.com/esl/amoc_rest/blob/1d615924/openapi.yaml
- Added and tested the new REST API endpoints
- Added support for `update_settings` in `amoc_dist`
- Fixed some minor issues with type specs
There is an increasing need to add tests for `amoc_dist` - this module is untested. This should be done in a separate issue.
See the commit messages below for more details.
=> REST API for scenario execution

doc/configuration.md, src/amoc_config/amoc_config_env.erl, src/amoc_config/amoc_config_utils.erl, src/amoc_config/amoc_config_verification.erl, src/amoc_distribution/amoc_cluster.erl, src/amoc_metrics.erl, src/amoc_scenario.erl, src/rest_api/amoc_api.erl, test/amoc_api_helper.erl, test/amoc_config_env_SUITE.erl, test/amoc_config_helper.erl, test/amoc_config_verification_SUITE.erl
removing possibility to provide configuration parameters values via erlang app env. variables.
this is a legacy functionality that rather increases the complexity than provides any benefits, it became confusing after splitting up amoc/scenarios/helpers into several erlang applications.
=> Amoc config env cleanup

Dockerfile, Makefile, doc/local-run.md, rebar.config, src/amoc.app.src
=> Fixing docsh dependency

src/amoc_controller.erl, src/amoc_users_sup.erl
As described in https://www.erlang.org/doc/man/erlang.html#process_flag_priority
> Priority level max is reserved for internal use in the Erlang runtime system, and is not to be used by others.
=> Do not use process priority max as per OTP guidelines

src/amoc_user.erl
As discussed in the internal communication channel, trying to report `normal_user_stop` still results in an abnormal exit, so this is buggy code, and altogether makes processes promoted to OTP `gen` processes to die with terrible crash reports. Logic is “call start, if it crashes, crash too”, so it makes sense to replace the `throw` in that `amoc_user:stop/1` function with `exit(shutdown)` and not have any `try ... catch`.
=> Let amoc user processes exit normally

Makefile, elvis.config, rebar.config, src/amoc_config/amoc_config.hrl, src/amoc_config/amoc_config_attributes.erl, src/amoc_config/amoc_config_env.erl, src/amoc_config/amoc_config_parser.erl, src/amoc_config/amoc_config_scenario.erl, src/amoc_controller.erl, src/amoc_coordinator/amoc_coordinator.erl, src/amoc_distribution/amoc_cluster.erl, src/amoc_distribution/amoc_dist.erl, src/amoc_throttle/amoc_throttle.erl, src/amoc_throttle/amoc_throttle_controller.erl, test/amoc_config_attributes_SUITE.erl, test/amoc_config_env_SUITE.erl, test/amoc_config_helper.erl, test/amoc_config_scenario_SUITE.erl, test/amoc_config_verification_SUITE.erl
This PR introduces the following changes:
• Possibility to customise parsing (de-serialisation) logic for env variables.
• small improvements for `amoc_config_scenario:update_settings/1` logic.
• extension of the tests.
=> Configurable env parser

integration_test/helper.sh, integration_test/start_test_cluster.sh, integration_test/test_add_new_node.sh, integration_test/test_amoc_cluster.sh, integration_test/test_distribute_scenario.sh, integration_test/test_run_scenario.sh, src/amoc_config/amoc_config_parser.erl
this PR introduces the following changes:
- exporting format/2 functin, since it's required for the REST API in `amoc-arsenal`
- fixing some functions in integration tests
=> Amoc arsenal

src/amoc_controller.erl
This happens when I run a scenario, this one finishes, and the status of the controller is left as `finished`, and then I want to run a new scenario but the controller complains that the status is invalid, when really I could perfectly start a new one.
Note that the controller has no tests on its own and therefore none are added here, actual tests want to be added later in a special PR.
=> Permit scenario start when the previous is finished too

src/amoc_controller.erl
Handle case where users already reached zero and there are no users to terminate on stop request. This can happen when the users die very fast for example, and therefore the count never really grows above zero. It can also happen if the test was left running for long enough for all the users to have finished their jobs.
Note that the controller has no tests on its own and therefore none are added here, actual tests want to be added later in a special PR.
=> Handle stop request with already zero users

src/amoc_code_server.erl
We want to accept this module. It's too complicated to reason why between Erlang's and Elixir's code servers these would result in different paths and hence we simply want to let this pass as it is a sufficiently uncommon edge-case.
=> This happens when running the Elixir code_server

guides/amoc_livebook.livemd, rebar.config
To be merged after #162, as this guide uses some metrics defined there.
Once all is merged before this, the final 3.0.0 should be released an the hex install for amoc should be updated.
=> Add livebook guide example

guides/configuration.md, src/amoc_config/amoc_config_env.erl, src/amoc_config/amoc_config_utils.erl, test/amoc_config_env_SUITE.erl, test/amoc_config_helper.erl
this PR introduces the following changes:
• documentation update
• fix for the `config_parser_mod` configuration parameter
=> Documentation update

guides/telemetry.md, src/amoc_coordinator/amoc_coordinator_worker.erl
Indicates an action is about to be triggered, either by enough users in the group or by timeout.
=> Add telemetry event for a coordinator trigger

src/coordinator/amoc_coordinator.erl, src/coordinator/amoc_coordinator_sup.erl, test/amoc_coordinator_SUITE.erl
This comes from when the name was the name of a registered process, and
hence the Erlang registry required it be an atom, but now it is an
opaque term stored in a persistent term, hence allowing the flexibility
for it to be any term allows us to create coordinators dynamically.
One example of when this might be desired is when coordinating members
of a groupchat: when the groupchat is created, a coordinator is created
with the name of the groupchat, and the members will add themselves to
this coordinator. This way, they can coordinate setting presences and
messages within the namespace of that room alone.
=> Allow any term to be a coordinator name

.github/workflows/ci.yml, guides/coordinator.md, guides/telemetry.md, guides/throttle.md, rebar.config, rebar.lock, src/throttle/amoc_throttle.erl, src/throttle/amoc_throttle_config.erl, src/throttle/amoc_throttle_controller.erl, src/throttle/amoc_throttle_pool.erl, src/throttle/amoc_throttle_pooler.erl, src/throttle/amoc_throttle_process.erl, src/throttle/amoc_throttle_runner.erl, src/throttle/amoc_throttle_sup.erl, test/throttle_SUITE.erl
Making the API for throttle more friendly to use
=> Throttle api

.github/workflows/ci.yml, rebar.config, test/amoc_config_scenario_SUITE.erl
Support for OTP28.
Also, a test became flaky after the fact that `ets:tab2list/1` might return values in a different order in different versions of OTP, so we here just want to capture the value and compare after sorting.
=> Upgrade dependencies and runtime versions
